# Build configuration for Eyelash Corne keyboard
# Builds left half with ZMK Studio, right half standard, and settings reset
---
include:
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_left_studio
  - board: eyelash_corne_right
    shield: nice_view
  - board: nice_nano_v2
    shield: settings_reset
